---
# tasks file for haproxy
- name: Ensure haproxy is present.
  yum:
    name: haproxy
    state: present

- name: Copying haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Enable the haproxy service
  service:
    name: haproxy
    state: started
    enabled: true

